# Generated by Django 2.1.2 on 2018-11-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualcomfort',
            old_name='answer',
            new_name='ALPHA',
        ),
        migrations.RenameField(
            model_name='visualcomfort',
            old_name='entry1',
            new_name='ALT',
        ),
        migrations.RenameField(
            model_name='visualcomfort',
            old_name='entry2',
            new_name='EDW',
        ),
    ]
